### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by mdudek** [mdg-soc-19/smooth-sort#2]
Is it possible to add support for null safety ?

**Comment by hemilpanchiwala** [comment]
@mdudek, 
Currently, I would not be able to give enough time due to some other engagements. However, it would be great if you could make a PR adding this support and I would be keen to help with it.

**Comment by mdudek** [comment]
@hemilpanchiwala ,
I have just submitted a PR #3  ;-)

**Comment by hemilpanchiwala** [comment]
@mdudek, Closing the issue as solved!
